services:
  web:
    stdin_open: true
    tty: true
    image: ghodsehimanshu17295665/django-app:latest
    container_name: django-app

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: always
  