version: '3'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    entrypoint: ./server-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - webnet
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: securepassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  postgres_data:
