services:
  - type: web
    name: himanshu-task
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=task.settings_build
    startCommand: |
      python manage.py migrate && gunicorn task.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanagement
          property: connectionString
databases:
  - name: taskmanagement
