name: "Lint-Server"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install black~=23.0
      - run: black .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install flake8
      - run: flake8

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: taskmanagement
          POSTGRES_USER: taskuser
          POSTGRES_PASSWORD: securepassword123
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U taskuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      CI: "true"
      SECRET_KEY: "test-secret-key"
      EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          export PGPASSWORD=$POSTGRES_PASSWORD
          until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do
            echo "Database not ready - sleeping"
            sleep 2
          done
          echo "Database connection established!"

      - name: Run migrations
        run: python manage.py migrate

      - name: Run Django tests
        run: python manage.py test --verbosity=2
